### ISSUE TITLE
Custom Netlify configuration properties

### ISSUE THREAD

**Issue by 8eecf0d2** [8eecf0d2/netlify-local#12]
In addition to #11, the Netlify configuration could also be used for other **netlify-local** options.

```toml
[plugins.local.webpack]
  config = "webpack.js"
[plugins.local.server]
  static = true
  lambda = true
  certificates = "private/certs"
  port = 9000
[plugins.local.functions]
  source = "src/lambda/ts"
  files = [
    "foo.js",
    "nested/bar.js"
  ]
```

This isn't as pretty as I'd like but I'm new to toml so maybe there's a better way to write this
