### ISSUE TITLE
Disable functions if build.functions is not set

### ISSUE THREAD

**Issue by jayvdb** [8eecf0d2/netlify-local#28]
Currently there is a backtrace if `build.functions` doesnt exist in the toml file.

That should disable the lambda , allowing basic static site serving without cli extra flags.

**Comment by 8eecf0d2** [comment]
Will double check that `build.functions` is optional in `netlify.toml` docs - otherwise will implement as suggested.

**Comment by jayvdb** [comment]
Ive just tested https://github.com/8eecf0d2/netlify-local/issues/12 , and I can use the following in `netlify.toml` to make this problem less important.

```toml
[plugins.local.server]
  static = true
  lambda = false
  port = 8100
```
