### ISSUE TITLE
express: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by jayvdb** [8eecf0d2/netlify-local#29]
I've not dug into this problem, so I dont know the exact cause.
```
[netlify-local] TypeError: Cannot read property 'length' of undefined
    at pathtoRegexp (/home/jayvdb/vs/node/8.13.0/lib/node_modules/netlify-local/node_modules/path-to-regexp/index.js:67:49)
    at new Layer (/home/jayvdb/vs/node/8.13.0/lib/node_modules/netlify-local/node_modules/express/lib/router/layer.js:45:17)
    at Function.use (/home/jayvdb/vs/node/8.13.0/lib/node_modules/netlify-local/node_modules/express/lib/router/index.js:464:17)
    at Function.<anonymous> (/home/jayvdb/vs/node/8.13.0/lib/node_modules/netlify-local/node_modules/express/lib/application.js:220:21)
    at Array.forEach (<anonymous>)
    at Function.use (/home/jayvdb/vs/node/8.13.0/lib/node_modules/netlify-local/node_modules/express/lib/application.js:217:7)
    at Server.routeStatic (/home/jayvdb/vs/node/8.13.0/lib/node_modules/netlify-local/.dist/server.js:95:22)
    at Server.initialize (/home/jayvdb/vs/node/8.13.0/lib/node_modules/netlify-local/.dist/server.js:82:14)
    at new Server (/home/jayvdb/vs/node/8.13.0/lib/node_modules/netlify-local/.dist/server.js:66:14)
    at Object.<anonymous> (/home/jayvdb/vs/node/8.13.0/lib/node_modules/netlify-local/.dist/cli.js:80:30)
```

netlify.toml:
```toml
[build]
  command = 'export PATH=./.ci/bin/:"$PATH" && build-netlify'
  publish = 'www'

[[redirects]]
  from = '/api/*'
  to = 'http://localhost:8000/:splat'
  status = 200
  force = true

[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200
```

I can work around this by editing /home/jayvdb/vs/node/8.13.0/lib/node_modules/netlify-local/node_modules/path-to-regexp/index.js function `pathtoRegexp` to add

```js
if (path === undefined) {
    return new RegExp();
  }
```

The site seems rather ok, with that hack, but ive not exhaustively tested yet

**Comment by 8eecf0d2** [comment]
Interesting, I thought the routing logic (although chaotic) was pretty sound  - will look at simplifying logic and hopefully find this bug along the way.

**Comment by jayvdb** [comment]
Could this be a bug upstream in `express`?

I can give you parts of the content files being served if it helps, especially privately.
Trying to create a public version might be a bit time consuming.

If you are not sure where the problem is, I can put one of our engineers on to help solve it.

**Comment by 8eecf0d2** [comment]
@jayvdb yeah from my understanding this is issue is caused by passing an illegal value to the `express` router - I've ran the server redirect test with those two redirects and nothing errors.
https://github.com/8eecf0d2/netlify-local/blob/77aa481e62bdc2b0eef9f5c348f8c25dd2cf4e39/test/ts/server.ts#L37-L52

Can you confirm if the error is thrown on startup / initialization or when a client hits the route?

**Comment by jayvdb** [comment]
It occurs on startup, before serving anything.

**Comment by 8eecf0d2** [comment]
Righto, so most likely in the `Server.routeStatic` I'm [adding a route without a path](https://stackoverflow.com/questions/52132243/general-nodejs-express-error-when-declaring-routes-typeerror-cannot-read-pro)...

I think a reasonable way to solve this is by adding more logging behind a flag and then checking what path `Server.routeStatic` is having issues with.

**Comment by 8eecf0d2** [comment]
Actually, scrap that, issue is caused by a missing `build.base` property in `netlify.toml`.
https://github.com/8eecf0d2/netlify-local/blob/77aa481e62bdc2b0eef9f5c348f8c25dd2cf4e39/src/ts/server.ts#L63

Can you add test with `base = ""`
```toml
[build]
  base = ''
  command = 'export PATH=./.ci/bin/:"$PATH" && build-netlify'
  publish = 'www'

...
```
